version: '3.7'
services:
  web:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:80
    volumes:
      - './:/var/www/html/'
      #      - './config/apache/apache-config.conf:/etc/apache2/sites-enabled/000-default.conf'
      #      - './config/apache/ports.conf:/etc/apache2/ports.conf'
      #      - './config/php/php.ini:/etc/php/7.4/apache2/php.ini'
#      - '.xdebug.ini:/etc/php/7.4/mods-available/xdebug.ini'
    networks:
      frontnet:
        ipv4_address: 172.30.1.2
  db:
    image: mariadb:10.5.8
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      frontnet:
        ipv4_address: 172.30.1.4

networks:
  frontnet:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16